// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo.Minimalist.Api.Data;

#nullable disable

namespace Todo.Minimalist.Api.Data.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20250920162521_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Todo.Minimalist.Api.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e1c1d1-0000-0000-0000-000000000001"),
                            IsDone = false,
                            Title = "Aprender .NET 10"
                        },
                        new
                        {
                            Id = new Guid("a1e1c1d1-0000-0000-0000-000000000002"),
                            IsDone = true,
                            Title = "Criar API Minimalista"
                        },
                        new
                        {
                            Id = new Guid("a1e1c1d1-0000-0000-0000-000000000003"),
                            IsDone = false,
                            Title = "Testar Seed Data"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
