name: Build & Test
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:          
            dotnet-version: '10.x.x'

      - name: Restore
        run: dotnet restore src/Todo.Minimalist.Api/Todo.Minimalist.Api.sln

      - name: Run dotnet format (code analysis)
        run: dotnet format src/Todo.Minimalist.Api/Todo.Minimalist.Api.sln --verify-no-changes --severity error

      - name: Build
        run: dotnet build --configuration Release src/Todo.Minimalist.Api/Todo.Minimalist.Api.sln --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test src/Todo.Minimalist.Api.Tests/Todo.Minimalist.Api.Tests.csproj --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=TestResults/coverage/ \
            /p:Threshold=80 \
            /p:ThresholdType=line \
            /p:FailWhenCoverageBelowThreshold=true

      - name: Generate coverage report
        run: |
          dotnet tool restore
          dotnet reportgenerator \
            -reports:src/TestResults/coverage/coverage.cobertura.xml \
            -targetdir:src/TestResults/coverage/html \
            -reporttypes:HtmlSummary;Badge

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: src/TestResults/coverage/html

