name: Build & Test
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x.x'

      - name: Restore
        run: dotnet restore src/Todo.Minimalist.Api/Todo.Minimalist.Api.sln

      - name: Build
        run: dotnet build --configuration Release src/Todo.Minimalist.Api/Todo.Minimalist.Api.sln

      - name: Test
        run: dotnet test src/Todo.Minimalist.Api.Tests/Todo.Minimalist.Api.Tests.csproj --no-build --framework net10.0 --verbosity normal